/**
 * Accurate English catalog (titles + short descriptions) for all tools.
 * Used by build-en-pages.mjs → i18n-en.js + /en/** shells.
 */
export const EN_CATEGORIES = {
  viral: 'Trending tools',
  creator: 'Creator toolkit',
  fun: 'Fun & quizzes',
  life: 'Daily life',
  utility: 'Utilities',
  media: 'Media',
  editor: 'Text editor',
  security: 'Security',
  dev: 'Developer',
  japan: 'Japan themes',
  world: 'World',
  symbols: 'Symbols',
  culture: 'Culture',
  spiritual: 'Spiritual',
};

/** @type {Record<string, { title: string, desc: string }>} */
export const EN_TOOLS = {
  'threads-persona-analyzer': { title: 'Threads persona analyzer', desc: 'Fun quiz for social persona and share-card export.' },
  'mortgage-calculator': { title: 'Mortgage / Youth loan calculator', desc: '2026 mortgage and New Youth loan rates with grace period.' },
  'llm-api-cost-calculator': { title: 'LLM API cost calculator', desc: 'Estimate GPT / Claude / Gemini monthly USD and TWD cost.' },
  'invoice-checker': { title: 'Invoice lottery checker', desc: 'Match invoice last three digits by period and share results.' },
  'income-tax-estimator': { title: 'Income tax estimator', desc: 'Quick progressive income-tax estimate for filing season.' },
  'meeting-cost-calculator': { title: 'Meeting cost calculator', desc: 'People × hourly rate × duration = meeting burn rate.' },
  'daily-fortune-card': { title: 'Daily fortune share card', desc: 'Birthday fortune card ready for Stories.' },
  'chat-screenshot-maker': { title: 'Chat screenshot maker', desc: 'Fake LINE / iMessage bubbles for memes.' },
  'ig-grid-splitter': { title: 'IG grid splitter', desc: 'Split one image into a 9-grid for Instagram.' },
  'youtube-thumbnail-factory': { title: 'YouTube thumbnail factory', desc: 'Bold 1280×720 thumbnail templates.' },
  'overtime-leave-calculator': { title: 'Overtime & leave calculator', desc: 'Estimate overtime pay and annual leave days.' },
  'labor-health-insurance': { title: 'Labor/health insurance tiers', desc: 'Lookup insured salary tiers from monthly pay.' },
  'avatar-safe-zone': { title: 'Avatar safe zone', desc: 'Preview round/square crop so faces are not cut off.' },
  'resume-photo-spec': { title: 'Resume photo specs', desc: 'ID photo crop with blue / white / red backgrounds.' },
  'hashtag-organizer': { title: 'Hashtag organizer', desc: 'Group and copy hashtags for posts.' },
  'gpa-calculator': { title: 'GPA calculator', desc: 'Weighted GPA from credits and grades.' },
  'vehicle-loan-calculator': { title: 'Vehicle loan calculator', desc: 'Car / scooter loan monthly payment estimate.' },
  'speech-time-estimator': { title: 'Speech time estimator', desc: 'Estimate talk minutes from word count and pace.' },
  'video-to-gif': { title: 'Video clip / GIF export', desc: 'Pick a local video range and export a short clip.' },
  'pdf-page-reorder': { title: 'PDF page reorder', desc: 'Reorder scanned pages locally without uploading.' },
  'audio-notes-summarizer': { title: 'Audio notes summarizer', desc: 'Turn transcripts into highlights and to-dos.' },
  'link-preview-card': { title: 'Link preview card', desc: 'Custom title and image for social preview cards.' },

  'ig-font-generator': { title: 'IG fancy font generator', desc: 'Unicode art fonts for Instagram and Threads.' },
  'image-compressor': { title: 'Image compressor', desc: 'Local Canvas JPEG / WebP compression.' },
  'labor-retirement-calculator': { title: 'Labor pension calculator', desc: 'Estimate labor pension / insurance charts.' },
  'instagram-caption-formatter': { title: 'Caption line-break formatter', desc: 'Convert line breaks to social-safe spaces.' },
  'meme-caption-generator': { title: 'Meme caption generator', desc: 'Classic meme templates with top/bottom text.' },
  'line-image-preview-cropper': { title: 'LINE safe-crop preview', desc: '1:1 safe ratios so chat previews keep faces.' },
  'markdown-to-html-cleaner': { title: 'Markdown to clean HTML', desc: 'Semantic HTML without inline CSS.' },
  'password-generator-pro': { title: 'Strong password generator', desc: 'Cryptographically random passwords.' },
  'speech-to-text-notebook': { title: 'Speech-to-text notebook', desc: 'Web Speech API notes you can copy.' },
  'qr-code-beautifier': { title: 'Gradient QR beautifier', desc: 'Rounded gradient QR codes on Canvas.' },

  'rp-test': { title: 'Personality fun test', desc: 'Name-based personality quiz for entertainment.' },
  'fortune-stick': { title: 'Online fortune sticks', desc: 'Draw temple fortune sticks and interpret.' },
  'reaction-test': { title: 'Reaction speed test', desc: 'Click as soon as you see the cue.' },
  'lucky-draw': { title: 'Lucky draw wheel', desc: 'Fair online raffle powered by RNG.' },
  'mind-reader': { title: 'Mind reader', desc: 'Classic mind-reading trick for fun.' },
  'zodiac': { title: 'Zodiac & Chinese zodiac', desc: 'Daily horoscope for light reference.' },
  'lucky-number': { title: 'Lucky numbers', desc: 'Generate lucky numbers for lottery dreams.' },
  'wishing-tree': { title: 'Wishing tree', desc: 'Make a wish — believe it or just smile.' },
  'jinyong': { title: 'Jin Yong character oracle', desc: 'Which wuxia hero matches you?' },
  'alchemist': { title: 'Human transmutation circle', desc: 'Body-composition ritual for Fullmetal fans.' },
  'ghost-story': { title: 'A Chinese Ghost Story', desc: 'Classic ghost-story feature page.' },

  'time': { title: 'World clock', desc: '432 time zones from fastest to slowest UTC.' },
  'calendar': { title: 'Perpetual calendar', desc: 'Solar/lunar calendar, almanac, and solar terms.' },
  'solar-terms': { title: '24 solar terms', desc: 'Chinese solar terms and seasonal culture.' },
  'currency': { title: 'World currencies', desc: '218 currencies with flags, symbols, and rates.' },
  'postal': { title: 'Country codes & postal', desc: 'Country dialing codes and postal lookup.' },
  'area-code': { title: 'International dialing codes', desc: 'Country calling codes before overseas calls.' },
  'voltage': { title: 'Voltage & plugs', desc: 'Outlet types and voltage for travel.' },
  'kinship': { title: 'Kinship calculator', desc: 'How to address relatives in Chinese.' },
  'parenting': { title: 'Parenting tools', desc: 'Family and parenting reference helpers.' },
  'car-brand': { title: 'Car brands', desc: 'Global logos grouped by automotive groups.' },
  'world-cup': { title: 'FIFA World Cup', desc: 'World Cup feature and fan hub.' },
  'datetime-calc': { title: 'Date & time calculator', desc: 'Days between dates or add/subtract N days.' },
  'english-date': { title: 'English date format', desc: 'Convert dates to July 11, 2026 style.' },
  'stopwatch': { title: 'Online stopwatch', desc: 'Timer and lap counter.' },
  'expiry-date': { title: 'Expiry date calculator', desc: 'Production date plus shelf life.' },
  'radix-converter': { title: 'Radix converter', desc: 'Binary, octal, decimal, hex conversion.' },
  'unit-length': { title: 'Length converter', desc: 'Meters, feet, miles, and more.' },
  'unit-weight': { title: 'Weight converter', desc: 'Kilograms, pounds, ounces.' },
  'unit-volume': { title: 'Volume converter', desc: 'Liters, gallons, milliliters.' },
  'unit-area': { title: 'Area converter', desc: 'm², ping, acres.' },
  'unit-byte': { title: 'Byte size converter', desc: 'KB, MB, GB, TB (1024-aware).' },
  'unit-temperature': { title: 'Temperature converter', desc: 'Celsius, Fahrenheit, Kelvin.' },
  'unit-pressure': { title: 'Pressure converter', desc: 'Pa, bar, psi conversion.' },
  'geo-coordinate': { title: 'Coordinate converter', desc: 'DMS ↔ decimal degrees for maps.' },
  'bmi': { title: 'BMI calculator', desc: 'Body mass index from height and weight.' },

  'settings': { title: 'Settings', desc: 'Theme, font, eye comfort, zoom, and accessibility.' },
  'calculatortool': { title: 'Online calculators', desc: 'Age, temperature, and everyday calculators.' },
  'id-generator': { title: 'Fake ID & card generator', desc: 'Test data only — not for real use.' },
  'phone': { title: 'Phone number generator', desc: 'Random numbers for form testing.' },
  'color-blindness': { title: 'Color blindness test', desc: 'Quick color-vision check.' },
  'screen-test': { title: 'Screen pixel test', desc: 'Find dead pixels and display issues.' },
  'screen-detect': { title: 'Browser & screen detect', desc: 'Browser and display capability report.' },
  'torch': { title: 'Torch / flashlight', desc: 'Screen or flash light when needed.' },
  'ip': { title: 'IP geolocation', desc: 'Lookup IP location and VPN sanity check.' },
  'qrcode-scan': { title: 'QR scanner', desc: 'Scan QR codes with your camera.' },
  'qrcode': { title: 'QR code generator', desc: 'Turn links into scannable QR codes.' },
  'guid': { title: 'GUID generator', desc: 'Bulk UUID v4 for test data.' },
  'random-number': { title: 'Random number generator', desc: 'Fair RNG within a chosen range.' },
  'whois': { title: 'Domain Whois', desc: 'Domain registration and expiry lookup.' },
  'batch-open-url': { title: 'Batch open URLs', desc: 'Open many URLs in tabs at once.' },
  'user-agent': { title: 'User-Agent viewer', desc: 'Inspect browser UA strings.' },
  'scriptures': { title: 'Scripture library', desc: 'Classics and sutras for online reading.' },

  'upload': { title: 'Temp file upload', desc: 'Temporary hosting — not long-term backup.' },
  'meitu': { title: 'Web photo beautify', desc: 'Quick beautify filters in the browser.' },
  'photo': { title: 'Photo editor', desc: 'Crop and color adjust without Photoshop.' },
  'exif': { title: 'Photo EXIF viewer', desc: 'Inspect photo metadata.' },
  'image-coordinate': { title: 'Image coordinates', desc: 'Pixel coordinates under the cursor.' },
  'music-player': { title: 'Web music player', desc: 'Play local audio in the browser.' },
  'media-player': { title: 'Web video player', desc: 'Drop in a file and play.' },
  'drawing': { title: 'Sketchpad', desc: 'Simple drawing board.' },
  'barcode': { title: 'Barcode generator', desc: 'EAN, Code128, and more.' },
  'image-compress': { title: 'Image compress', desc: 'Local JPG/PNG compression.' },

  'editor': { title: 'Online text editor', desc: 'Lightweight HTML text editing.' },
  'dedupe': { title: 'Remove duplicate lines', desc: 'Deduplicate URLs, names, or text.' },
  'case-converter': { title: 'Case converter', desc: 'UPPER / lower / Title Case.' },
  'chn-upper': { title: 'Chinese numeral uppercase', desc: 'Cheque-style Chinese numerals.' },
  'wordcount': { title: 'Word counter', desc: 'Words, lines, and paragraphs.' },
  'colorfont': { title: 'Gradient text', desc: 'Colorful gradient headings.' },
  'bbcode': { title: 'BBCode converter', desc: 'HTML ↔ BBCode.' },
  'unicode-converter': { title: 'Unicode converter', desc: 'Characters ↔ Unicode codes.' },
  'text-replace': { title: 'Find & replace', desc: 'Batch keyword replacement.' },
  'text-reverse': { title: 'Text reverse', desc: 'Reverse lines or characters.' },
  'line-number': { title: 'Add line numbers', desc: 'Number every line automatically.' },
  'text-to-html': { title: 'Text to HTML', desc: 'Newlines to <br> / paragraphs to <p>.' },
  'word-frequency': { title: 'Word frequency', desc: 'See which words appear most.' },
  'duplicate-check': { title: 'Similarity check', desc: 'How alike are two texts?' },
  'fancy-font': { title: 'Fancy English fonts', desc: 'Unicode fancy letters for social posts.' },
  'full-half': { title: 'Full/half-width converter', desc: 'Full-width ↔ half-width characters.' },

  'password': { title: 'Password security', desc: 'Generate strong passwords and check strength.' },
  'email-icon': { title: 'Email icon / obfuscation', desc: 'Email as image or obfuscated text vs scrapers.' },
  'textencrypt': { title: 'Text encrypt', desc: 'Local XOR + Base64 demo encryption.' },
  'longurl': { title: 'Expand short URLs', desc: 'Reveal bit.ly / t.co destinations.' },
  'url-crypto': { title: 'URL crypto', desc: 'Hex encode/decode URLs and legacy formats.' },
  'base64': { title: 'Base64 encode/decode', desc: 'Text and image Base64 conversion.' },
  'hash-tool': { title: 'MD5 / SHA hash', desc: 'MD5, SHA-1, SHA-256 checksums.' },
  'aes-crypto': { title: 'AES encrypt/decrypt', desc: 'Symmetric AES playground.' },
  'morse-code': { title: 'Morse code', desc: 'Text ↔ Morse dots and dashes.' },

  'color': { title: 'Web color palette', desc: 'Pick colors and convert codes.' },
  'favicon': { title: 'Favicon generator', desc: 'Create site favicons quickly.' },
  'shorturl': { title: 'URL shortener', desc: 'Shorten long links for sharing.' },
  'url-encoder': { title: 'URL encode/decode', desc: 'Percent-encoding for URLs.' },
  'css-formatter': { title: 'CSS formatter', desc: 'Beautify or minify CSS.' },
  'html-js-formatter': { title: 'HTML & JS formatter', desc: 'Format HTML/JS code.' },
  'viewsource': { title: 'View page source', desc: 'Inspect remote page source.' },
  'html-converter': { title: 'HTML code converter', desc: 'HTML / PHP / JS encoding helpers.' },
  'runcode': { title: 'Online code runner', desc: 'Write and run snippets instantly.' },
  'unicode': { title: 'UTF-8 ↔ Unicode', desc: 'Character encoding conversion.' },
  'punycode': { title: 'Punycode domains', desc: 'Chinese domains ↔ xn-- Punycode.' },
  'http-status': { title: 'HTTP status codes', desc: '200 happy, 404 sad, 500 sleep.' },
  'html-entities': { title: 'HTML entities', desc: '&nbsp; &copy; reference table.' },
  'keycode': { title: 'KeyCode detector', desc: 'See which key code you pressed.' },
  'unicode-table': { title: 'Unicode table', desc: 'Browse Unicode characters.' },
  'big5': { title: 'Big5 code table', desc: 'Traditional Chinese Big5 mapping.' },
  'keyboard-mouse': { title: 'Keyboard & mouse test', desc: 'Test input devices.' },
  'seo-search': { title: 'SEO search links', desc: 'Index, backlinks, robots, sitemap checks.' },
  'sitemap': { title: 'Sitemap generator', desc: 'XML / HTML sitemaps for crawlers.' },
  'seo-keyword': { title: 'SEO keywords', desc: 'Keyword ranking helpers.' },
  'json-editor': { title: 'JSON editor', desc: 'Format, validate, and fold JSON.' },
  'sql-formatter': { title: 'SQL formatter', desc: 'Beautify or minify SQL.' },
  'regex-test': { title: 'Regex tester', desc: 'Live regular-expression matching.' },
  'crontab-calc': { title: 'Crontab calculator', desc: 'Next run times for cron expressions.' },
  'naming-converter': { title: 'Naming converter', desc: 'camelCase / snake_case / kebab-case.' },
  'json-to-typescript': { title: 'JSON to TypeScript', desc: 'Infer interfaces from JSON.' },
  'timestamp': { title: 'Timestamp converter', desc: 'Unix time ↔ human datetime.' },
  'timestamp-batch': { title: 'Batch timestamps', desc: 'Convert many timestamps at once.' },

  'japanese-shrine': { title: 'Japanese shrines', desc: 'Shrines by region, deities, etiquette, charms.' },
  'anime-hometown': { title: 'Anime hometowns', desc: 'Pilgrimage spots for Conan, Your Name, and more.' },
  'retro': { title: 'Showa / Taisho retro', desc: 'Warm wood retro vs modern Tokyo slider.' },
  'yokai': { title: 'Yokai night parade', desc: 'Flashlight hunt for hidden yokai.' },
  'yokocho': { title: 'Late-night alleys', desc: 'Lantern izakaya soundscapes.' },
  'gourmet': { title: 'B-grade gourmet map', desc: 'Budget street-food legends by region.' },
  'stay': { title: 'Hidden onsen machiya', desc: 'Machiya and secret lodgings, day/night mood.' },
  'fuji-views': { title: 'Twelve Fuji views', desc: 'Seasonal Fuji vistas and sea of clouds.' },
  'sakura-front': { title: 'Sakura front guide', desc: 'Early bloom to late sakura etiquette.' },
  'momiji-trail': { title: 'Autumn foliage trail', desc: 'Day forests and night illuminations.' },
  'matsuri-calendar': { title: 'Festival calendar', desc: 'Mikoshi, fireworks, drums by month.' },
  'hanabi-guide': { title: 'Fireworks guide', desc: 'Famous venues and night-sky mood.' },
  'torii-tunnel': { title: 'Torii tunnel', desc: 'Vermilion torii spotlight maze.' },
  'karesansui': { title: 'Dry landscape gardens', desc: 'Sand patterns, stones, and zen layouts.' },
  'kenrokuen': { title: 'Kenrokuen, Kanazawa', desc: 'Six excellences garden and tea streets.' },
  'otaru-canal': { title: 'Otaru canal', desc: 'Stone warehouses and canal lights.' },
  'nagoya-castle': { title: 'Nagoya Castle', desc: 'Golden shachi, palace, and castle town.' },
  'onsen-kyo': { title: 'Onsen town map', desc: 'Spring types, streets, bathing etiquette.' },
  'wagashi-scroll': { title: 'Wagashi seasons', desc: 'Seasonal sweets for tea gatherings.' },
  'aizome-kimono': { title: 'Indigo & kimono', desc: 'Aizome patterns and wear occasions.' },
  'railway-views': { title: 'Railway scenery', desc: 'Coast, mountain, and city train windows.' },
  'ama-shima': { title: 'Ama divers & Shima', desc: 'Pearl divers and Ise-Shima sea culture.' },
  'ghost-stations': { title: 'Ghost stations', desc: 'Foggy platforms and abandoned lines — safety first.' },
  'inari-fox': { title: 'Inari foxes', desc: 'Fox statues and Inari imagery.' },
  'samurai-armor': { title: 'Samurai armor', desc: 'Armor, blades, and family crests explained.' },
  'ukiyo-e-now': { title: 'Ukiyo-e then & now', desc: 'Classic prints vs modern streets.' },
  'kabukicho-neon': { title: 'Kabukicho neon', desc: 'Shinjuku neon nights with safety tips.' },

  'world-flags': { title: 'World flags', desc: 'Flags with capitals, languages, and meanings.' },
  'population': { title: 'World population', desc: 'Population ranks, growth, and structure.' },
  'coat-of-arms': { title: 'National coats of arms', desc: 'Emblems, symbolism, and history.' },
  'ethnic-china': { title: 'Chinese ethnic groups', desc: '56 ethnic groups of China.' },
  'national-anthem': { title: 'National anthems', desc: 'Lyrics with Chinese translation notes.' },
  'ufo': { title: 'Alien races (UFO)', desc: 'Speculative races, homeworlds, contact lore.' },
  'monster': { title: 'Chinese monsters', desc: 'Horror bestiary with cultural links.' },
  'national-symbol': { title: 'National symbols', desc: 'National animals, birds, and fish.' },

  'symbols-generator': { title: 'Emoticon builder', desc: 'Compose kaomoji at the cursor.' },
  'keyboard-symbols': { title: 'Special symbols', desc: 'Click to copy keyboard symbols.' },
  'emoji': { title: 'Emoji picker', desc: 'Click to copy emoji.' },
  'punctuation': { title: 'Punctuation library', desc: '852 punctuation and math symbols.' },
  'symbols-name': { title: 'Symbol names', desc: 'Chinese/English names for 239 symbols.' },
  'boshiamy': { title: 'Boshiamy symbols', desc: 'Boshiamy input code chart.' },
  'wubi': { title: 'Wubi special symbols', desc: 'Wubi input symbol keys.' },
  'emoticon': { title: 'Classic emoticons', desc: 'Text-face emoticons.' },
  'ubcode': { title: 'U+B charset', desc: 'Unicode / Big5 special characters.' },
  'alt-code': { title: 'Alt codes', desc: 'Alt+number special characters.' },
  'roman-numeral': { title: 'Roman numerals', desc: 'I V X L C D M converter.' },
  'suzhou-numeral': { title: 'Suzhou numerals', desc: 'Traditional commercial numerals.' },
  'strokes': { title: 'Strokes & radicals', desc: 'Stroke order, radicals, and components.' },

  'typing-teach': { title: 'Chinese IME tutorial', desc: 'Cangjie, Pinyin, Bopomofo, Wubi intro.' },
  'typing-practice': { title: 'Typing practice', desc: 'Finger drills beyond hunt-and-peck.' },
  'dictionary': { title: 'Chinese dictionary', desc: 'Look up characters and readings.' },
  'cangjie-dict': { title: 'Cangjie dictionary', desc: 'Cangjie decomposition lookup.' },
  'zh-converter': { title: 'Trad/simp converter', desc: 'Traditional ↔ Simplified Chinese.' },
  'zh-table': { title: 'Trad/simp character table', desc: 'One-to-one character mapping.' },
  'text-garbled': { title: 'Mojibake fixer', desc: 'Repair garbled copy-paste text.' },
  'pinyin': { title: 'Chinese to Pinyin', desc: 'Hanzi to Hanyu Pinyin.' },
  'pinyin-to-zh': { title: 'Pinyin to Chinese', desc: 'Reverse lookup from Pinyin.' },
  'pinyin-chart': { title: 'Pinyin chart', desc: 'Full Mandarin Pinyin table.' },
  'pinyin-syllable': { title: 'Pinyin syllable lookup', desc: 'Browse Pinyin syllables.' },
  'pinyin-phonics': { title: 'Pinyin phonics', desc: 'Practice Pinyin blending.' },
  'cangjie-chart': { title: 'Cangjie alphabet', desc: 'Letters and auxiliary shapes.' },
  'cangjie-practice': { title: 'Cangjie practice', desc: 'Speed drills for Cangjie.' },
  'bopomofo': { title: 'Zhuyin (Bopomofo)', desc: 'Zhuyin ↔ Pinyin conversion.' },
  'bopomofo-chart': { title: 'Zhuyin chart', desc: '37 Zhuyin symbols.' },
  'bopomofo-phonics': { title: 'Zhuyin phonics', desc: 'Practice Zhuyin blending.' },
  'bopomofo-index': { title: 'Zhuyin syllable index', desc: 'Fast syllable lookup.' },
  'bopomofo-table': { title: 'Zhuyin ↔ Pinyin table', desc: 'Side-by-side system map.' },
  'abc': { title: 'English alphabet', desc: '26 letters with pronunciation.' },

  'numerology': { title: 'Life path numerology', desc: 'Birthday number meanings.' },
  'enneagram': { title: 'Enneagram', desc: 'Nine personality types quiz.' },
  'chakra': { title: 'Seven chakras', desc: 'Chakra alignment quiz.' },
  'hawkins': { title: 'Hawkins consciousness levels', desc: 'Map of consciousness scale.' },
};
